# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2022-01-24T00:59:01+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Tag245(BaseModel):
    a: str = Field(..., title='A')


class Datafield(BaseModel):
    tag_245: Tag245


class MarcBibliographic(BaseModel):
    datafield: Datafield
    leader: Optional[str] = Field('01602cam a2200325 a 4500', title='Leader')
