"""Remove Test

Revision ID: 316471948903
Revises: b54d50c32946
Create Date: 2022-04-11 14:30:51.733571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '316471948903'
down_revision = 'b54d50c32946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_default_charset='utf8mb3',
    mariadb_engine='InnoDB'
    )
    # ### end Alembic commands ###
