"""Initial

Revision ID: b54d50c32946
Revises: 
Create Date: 2022-04-11 14:25:15.587166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b54d50c32946'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authority',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('format', sa.String(length=100), nullable=True),
    sa.Column('schema', sa.String(length=100), nullable=True),
    sa.Column('marc_record', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('marc', mysql.JSON(), nullable=True),
    sa.Column('logs', mysql.JSON(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('tag', sa.String(length=5), nullable=True),
    sa.Column('format', sa.String(length=100), nullable=True),
    sa.Column('schema', sa.String(length=100), nullable=True),
    sa.Column('marc_record', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hash_password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('authorship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authority_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('relation', sa.String(length=100), nullable=True),
    sa.Column('publicationyear', mysql.YEAR(), nullable=True),
    sa.ForeignKeyConstraint(['authority_id'], ['authority.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exemplar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=10), nullable=True),
    sa.Column('callnumber', sa.String(length=30), nullable=True),
    sa.Column('edition', sa.String(length=10), nullable=True),
    sa.Column('year', mysql.YEAR(), nullable=True),
    sa.Column('volume', sa.String(length=5), nullable=True),
    sa.Column('library', sa.String(length=30), nullable=True),
    sa.Column('shelf', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('collection', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authority_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('relation', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['authority_id'], ['authority.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_subject')
    op.drop_table('exemplar')
    op.drop_table('authorship')
    op.drop_table('user')
    op.drop_table('test')
    op.drop_table('subject')
    op.drop_table('item')
    op.drop_table('authority')
    # ### end Alembic commands ###
